#:schema node_modules/wrangler/config-schema.json
name = "lobechat-plugin-template"
main = "dist/index.js"
compatibility_date = "2025-02-26"
compatibility_flags = ["nodejs_compat"]
minify = true
logpush = false

services = [
  { binding = "MYSELF", service = "lobechat-plugin-template" }
]

[observability]
enabled = true
